export const defaultTheme = {
  colorMainForText: "darkslateblue",
  colorForHeaderAndFooter: "whitesmoke",
  colorWhite: "yellow",
  colorGray: "#f6f6f6",
  colorForSiteName: "indianred",
  colorForLightBackground: "lightblue",
  // colorForLightBackground: "rgba(217, 240, 118, 0.5)",
  colorForDarkBackground: "#ffeead",
  colorForNewIcon: "#ffb334",
  colorForSoftIcon: "#7fc92e",
  colorForButton: "darkorange",
  colorForButtonHover: "#F35714",
  colorForTitle: "darkgreen",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Pangolin", cursive',
  fontSizeDefault: "18px",
  footerHeight: "80px",
  pageWidth: "1519px"
};
