export const defaultTheme = {
  colorMainForText: "darkslateblue",
  colorForHeaderAndFooter: "whitesmoke",
  colorWhite: "yellow",
  colorGray: "#f6f6f6",
  colorForSiteName: "indianred",
  colorForForm: "#e7b1b1",
  colorForLightBackground: "lightblue",
  // colorForLightBackground: "rgba(217, 240, 118, 0.5)",
  colorForListBackground: "#ffeead",
  colorForNewIcon: "#ffb334",
  colorForIcon: "#7fc92e",
  colorForButton: "darkorange",
  colorForButtonHover: "#F35714",
  colorForTitle: "darkgreen",
  colorForCards: "rgba(0, 55, 255, 0.218)",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Pangolin", cursive',
  fontSizeDefault: "18px",
  footerHeight: "80px",
  pageWidth: "1280px"
};
